
import { Aircraft } from './types';

export const AIRCRAFT_DATA: Aircraft[] = [
  {
    id: "F22-RAPTOR",
    name: "F-22 Raptor",
    country: "USA",
    generation: "5",
    primaryRole: "Air Superiority",
    status: "Active",
    manufacturer: "Lockheed Martin / Boeing",
    firstFlight: "1997-09-07",
    unitCost: "$150M (Estimated flyaway)",
    summary: "The F-22 Raptor is a twin-engine stealth tactical fighter. Designed as an air superiority fighter, it incorporates sensor fusion and supercruise. It remains the gold standard for aerial dominance despite limited production.",
    techProfile: {
      airframe: "Titanium and carbon fiber composite structure with RAM.",
      propulsion: "2 × Pratt & Whitney F119-PW-100; 2D thrust vectoring.",
      performance: "Mach 2.25; Supercruise at Mach 1.82.",
      avionics: "AN/APG-77 AESA; AN/ALR-94 EW suite.",
      weapons: "Internal bays: AIM-120, AIM-9; 20mm Vulcan.",
      stealth: "High-degree passive stealth; RCS ~0.0001 m²."
    },
    ratings: { airToAir: 10, bvr: 10, dogfight: 9.5, avionics: 9.5, stealth: 10, multirole: 7, survivability: 10, overall: 9.8 },
    comparativeAnalysis: ["Superior stealth to Su-57/J-20.", "Higher energy retention than 4th-gen.", "Limited multirole compared to F-35."],
    futureOutlook: "Upgraded via Agile Raptor program. Service until 2040s.",
    relatedIds: ["F35-LIGHTNING", "SU57-FELON"]
  },
  {
    id: "F35-LIGHTNING",
    name: "F-35 Lightning II",
    country: "USA / NATO",
    generation: "5",
    primaryRole: "Multirole",
    status: "Active",
    manufacturer: "Lockheed Martin",
    firstFlight: "2006-12-15",
    unitCost: "$78M - $110M",
    summary: "A family of single-engine stealth multirole fighters. Designed for air superiority and strike, it excels in sensor fusion and networking, acting as a 'quarterback' in modern air combat.",
    techProfile: {
      airframe: "Three variants (A, B, C) for different service requirements.",
      propulsion: "1 × Pratt & Whitney F135-PW-100.",
      performance: "Mach 1.6; 50,000 ft ceiling.",
      avionics: "AN/APG-81 AESA; DAS; EOTS; HMDS.",
      weapons: "Internal bays for 4-6 missiles; External hardpoints.",
      stealth: "Optimized for X-band radar low observability."
    },
    ratings: { airToAir: 9, bvr: 10, dogfight: 8, avionics: 10, stealth: 9.5, multirole: 10, survivability: 9.5, overall: 9.4 },
    comparativeAnalysis: ["Industry-leading sensor fusion.", "Lower kinematic performance than F-22.", "Superior target ID capabilities."],
    futureOutlook: "Block 4 upgrades introduce significant processing power.",
    relatedIds: ["F22-RAPTOR", "KF21-BORAMAE"]
  },
  {
    id: "B21-RAIDER",
    name: "B-21 Raider",
    country: "USA",
    generation: "5",
    primaryRole: "Strike",
    status: "Testing",
    manufacturer: "Northrop Grumman",
    firstFlight: "2023-11-10",
    unitCost: "$750M (Estimated)",
    summary: "A next-generation stealth bomber designed for the USAF. It uses a flying wing design to achieve deep penetration in highly contested environments. It is the first '6th-gen look' aircraft.",
    techProfile: {
      airframe: "Advanced flying wing; seamless RAM integration.",
      propulsion: "Classified twin-engine configuration.",
      performance: "Subsonic long-range; massive internal payload.",
      avionics: "Cloud-native digital architecture; open systems design.",
      weapons: "Nuclear and conventional capable; stand-off and direct munitions.",
      stealth: "Extreme broadband stealth designed for the 21st-century radar."
    },
    ratings: { airToAir: 1, bvr: 4, dogfight: 1, avionics: 10, stealth: 10, multirole: 8, survivability: 10, overall: 9.2 },
    comparativeAnalysis: ["Significantly more advanced than B-2.", "Designed for easier maintenance than previous stealth platforms.", "Smaller payload than B-2 but higher survivability."],
    futureOutlook: "Initial operating capability expected by mid-2020s.",
    relatedIds: ["F22-RAPTOR", "F35-LIGHTNING"]
  },
  {
    id: "A10C-WARTHOG",
    name: "A-10C Thunderbolt II",
    country: "USA",
    generation: "4",
    primaryRole: "Attack",
    status: "Active",
    manufacturer: "Fairchild Republic",
    firstFlight: "1972-05-10",
    unitCost: "$18.8M",
    summary: "Commonly known as the 'Warthog', this aircraft is designed around the GAU-8 Avenger 30mm cannon. It is a rugged close air support platform with legendary durability.",
    techProfile: {
      airframe: "Titanium 'bathtub' pilot protection; redundant controls.",
      propulsion: "2 × General Electric TF34-GE-100 turbofans.",
      performance: "Low speed (Mach 0.5); High loiter time.",
      avionics: "Modernized cockpit with digital displays; SADL data link.",
      weapons: "30mm GAU-8 Cannon; AGM-65 Maverick; Hydra 70 rockets.",
      stealth: "None. Relies on low altitude and armor."
    },
    ratings: { airToAir: 2, bvr: 2, dogfight: 4, avionics: 7, stealth: 1, multirole: 6, survivability: 9.5, overall: 6.5 },
    comparativeAnalysis: ["Unmatched gun performance.", "Low survivability against modern SAMs.", "Economical CAS platform."],
    futureOutlook: "Phased retirement planned; being replaced by F-35 in contested CAS roles.",
    relatedIds: ["SU25-FROGFOOT", "SU34-FULLBACK"]
  },
  {
    id: "MIRAGE-2000-5",
    name: "Mirage 2000-5",
    country: "France",
    generation: "4",
    primaryRole: "Multirole",
    status: "Active",
    manufacturer: "Dassault Aviation",
    firstFlight: "1978-03-10",
    unitCost: "$35M",
    summary: "A delta-wing multirole fighter. Highly agile and efficient, the -5 variant upgraded the radar and weapons, making it a viable modern combatant for several nations.",
    techProfile: {
      airframe: "Pure delta wing; unstable flight design for agility.",
      propulsion: "1 × Snecma M53-P2 afterburning turbofan.",
      performance: "Mach 2.2; Excellent instantaneous turn rate.",
      avionics: "RDY radar (multi-target); modernized cockpit.",
      weapons: "MICA IR/EM missiles; Magic 2; SCALP EG.",
      stealth: "Limited. Standard 4th-gen profile."
    },
    ratings: { airToAir: 8, bvr: 7.5, dogfight: 9, avionics: 7, stealth: 3, multirole: 8, survivability: 7, overall: 7.6 },
    comparativeAnalysis: ["Higher agility than contemporary F-16 variants.", "Lower payload capacity than F-15 or Rafale.", "Very high reliability."],
    futureOutlook: "Being replaced by Rafale in French service; active in Greece, UAE, and Taiwan.",
    relatedIds: ["RAFALE", "F16V-VIPER"]
  },
  {
    id: "SU57-FELON",
    name: "Su-57 Felon",
    country: "Russia",
    generation: "5",
    primaryRole: "Multirole",
    status: "Active",
    manufacturer: "Sukhoi",
    firstFlight: "2010-01-29",
    unitCost: "$35M - $45M (Estimated)",
    summary: "The Su-57 is a twin-engine stealth multirole fighter. It features extreme maneuverability and side-looking radars. Stealth is optimized for frontal detection.",
    techProfile: {
      airframe: "Blended wing body; extensive use of composites.",
      propulsion: "2 × AL-41F1; Future: Izdeliye 30.",
      performance: "Mach 2.0; Supercruise capable.",
      avionics: "Sh121 radio electronic system; N036 Byelka radar.",
      weapons: "Internal bays; various air-to-air/surface missiles.",
      stealth: "Frontal stealth focus; RCS larger than F-22."
    },
    ratings: { airToAir: 9.5, bvr: 9, dogfight: 10, avionics: 8.5, stealth: 8, multirole: 9, survivability: 9, overall: 9.1 },
    comparativeAnalysis: ["Exceptional agility due to 3D thrust vectoring.", "Stealth inferior to US peers.", "Innovative sensor distribution."],
    futureOutlook: "Production ramping up slowly; AL-51F1 engine integration is key.",
    relatedIds: ["F22-RAPTOR", "SU35-FLANKER"]
  },
  {
    id: "MIG29-FULCRUM",
    name: "MiG-29 Fulcrum",
    country: "Russia / Eastern Europe",
    generation: "4",
    primaryRole: "Air Superiority",
    status: "Active",
    manufacturer: "Mikoyan",
    firstFlight: "1977-10-06",
    unitCost: "$22M",
    summary: "A twin-engine air superiority fighter designed to counter the F-15 and F-16. It is highly agile at short ranges but traditionally hampered by limited range.",
    techProfile: {
      airframe: "Steel and aluminum alloy; high lift coefficient.",
      propulsion: "2 × Klimov RD-33 turbofans.",
      performance: "Mach 2.25; Excellent low-speed handling.",
      avionics: "N019 radar; IRST; Helmet-mounted sight (pioneer).",
      weapons: "R-73 (HOBS); R-27; 30mm GSh-30-1 cannon.",
      stealth: "None. Large visual and radar signature."
    },
    ratings: { airToAir: 8.5, bvr: 6, dogfight: 9.5, avionics: 6, stealth: 2, multirole: 5, survivability: 6.5, overall: 7.2 },
    comparativeAnalysis: ["Superior dogfighter to early F-16s.", "Poor avionics and BVR range compared to West.", "Robust engine operation from dirt runways."],
    futureOutlook: "Legacy fleets being modernized to SMT or K standards; largely replaced by Su-30/35.",
    relatedIds: ["SU35-FLANKER", "F16V-VIPER"]
  },
  {
    id: "MQ9-REAPER",
    name: "MQ-9 Reaper",
    country: "USA",
    generation: "4",
    primaryRole: "Strike",
    status: "Active",
    manufacturer: "General Atomics",
    firstFlight: "2001-02-02",
    unitCost: "$32M",
    summary: "The primary hunter-killer UAV for the USAF. It provides long-endurance ISR and precision strike capability from remote locations.",
    techProfile: {
      airframe: "Composite lightweight airframe; high aspect ratio wings.",
      propulsion: "1 × Honeywell TPE331-10 turboprop.",
      performance: "24-30 hours endurance; Max altitude 50,000 ft.",
      avionics: "AN/DAS-1 MTS-B; AN/APY-8 Lynx SAR radar.",
      weapons: "AGM-114 Hellfire; GBU-12 Paveway; AIM-92 Stinger.",
      stealth: "Low RCS compared to heavy jets, but not stealth-optimized."
    },
    ratings: { airToAir: 2, bvr: 3, dogfight: 1, avionics: 9, stealth: 5, multirole: 8, survivability: 4, overall: 6.8 },
    comparativeAnalysis: ["Unmatched loiter time.", "Extremely vulnerable to manned fighters.", "Highly cost-effective ISR."],
    futureOutlook: "Evolving for maritime surveillance; MQ-9B SkyGuardian variants entering service.",
    relatedIds: ["F35-LIGHTNING", "A10C-WARTHOG"]
  },
  {
    id: "F117-NIGHTHAWK",
    name: "F-117 Nighthawk",
    country: "USA",
    generation: "4",
    primaryRole: "Strike",
    status: "Retired",
    manufacturer: "Lockheed Corporation",
    firstFlight: "1981-06-18",
    unitCost: "$42.6M",
    summary: "The world's first operational stealth aircraft. Its faceted design reflected radar waves away from the source. It was 'retired' but still flies for testing.",
    techProfile: {
      airframe: "Faceted aluminum structure with RAM.",
      propulsion: "2 × General Electric F404-F1D2 engines.",
      performance: "Subsonic (Mach 0.92); No radar (passive sensors only).",
      avionics: "IRADS; DLIR; FLIR; inertial navigation.",
      weapons: "2 internal bays; GBU-10/12/27 laser-guided bombs.",
      stealth: "Groundbreaking faceted stealth; ultra-low RCS."
    },
    ratings: { airToAir: 1, bvr: 1, dogfight: 1, avionics: 6, stealth: 9, multirole: 3, survivability: 8, overall: 6.2 },
    comparativeAnalysis: ["First of its kind.", "Poor flight characteristics (unstable).", "Obsolete compared to modern curved stealth."],
    futureOutlook: "Used as 'aggressors' or 'stealth targets' for testing new radars.",
    relatedIds: ["F22-RAPTOR", "B21-RAIDER"]
  },
  {
    id: "EUROFIGHTER-TYPHOON",
    name: "Eurofighter Typhoon",
    country: "Europe",
    generation: "4.5",
    primaryRole: "Multirole",
    status: "Active",
    manufacturer: "Eurofighter GmbH",
    firstFlight: "1994-03-27",
    unitCost: "$100M - $120M",
    summary: "A highly agile multirole fighter with world-class dogfighting and BVR capabilities. It is the core of European air defense.",
    techProfile: {
      airframe: "Canard delta; carbon-fiber composites.",
      propulsion: "2 × Eurojet EJ200; supercruise capable.",
      performance: "Mach 2.0+; Supercruise Mach 1.5.",
      avionics: "CAPTOR-M/E radar; PIRATE IRST.",
      weapons: "13 hardpoints; Meteor; Storm Shadow.",
      stealth: "Frontal RCS reduction."
    },
    ratings: { airToAir: 9.5, bvr: 9.5, dogfight: 9.5, avionics: 9, stealth: 6.5, multirole: 9, survivability: 8.5, overall: 8.9 },
    comparativeAnalysis: ["Kinematically superior to 4th-gen.", "Meteor integration is a massive BVR edge.", "High maintenance cost."],
    futureOutlook: "LTE program will modernize cockpit/EW.",
    relatedIds: ["RAFALE", "F15EX-EAGLE"]
  },
  {
    id: "RAFALE",
    name: "Dassault Rafale",
    country: "France",
    generation: "4.5",
    primaryRole: "Multirole",
    status: "Active",
    manufacturer: "Dassault Aviation",
    firstFlight: "1986-07-04",
    unitCost: "$90M - $110M",
    summary: "An 'omnirole' fighter capable of air supremacy, strike, and nuclear deterrence. It is carrier-capable and features the SPECTRA EW system.",
    techProfile: {
      airframe: "Close-coupled canard-delta.",
      propulsion: "2 × Snecma M88-4E.",
      performance: "Mach 1.8; Supercruise Mach 1.4.",
      avionics: "RBE2 AA AESA; SPECTRA EW.",
      weapons: "Meteor; SCALP; Exocet; ASMP-A.",
      stealth: "Moderate RCS reduction."
    },
    ratings: { airToAir: 9, bvr: 9.2, dogfight: 9.5, avionics: 9.5, stealth: 7, multirole: 10, survivability: 9, overall: 9.0 },
    comparativeAnalysis: ["Best-in-class EW (SPECTRA).", "Superior multirole to Typhoon.", "Carrier-ready design."],
    futureOutlook: "F4/F5 standards focus on collaborative combat.",
    relatedIds: ["EUROFIGHTER-TYPHOON", "F/A18E-SUPERHORNET"]
  },
  {
    id: "F15EX-EAGLE",
    name: "F-15EX Eagle II",
    country: "USA",
    generation: "4++",
    primaryRole: "Multirole",
    status: "Active",
    manufacturer: "Boeing",
    firstFlight: "2021-02-02",
    unitCost: "$87M",
    summary: "A modernized digital evolution of the F-15. It features massive payload capacity and the fastest mission computer in any fighter.",
    techProfile: {
      airframe: "Strengthened F-15 frame; Fly-by-wire.",
      propulsion: "2 × GE F110-GE-129.",
      performance: "Mach 2.5; 29,500 lbs payload.",
      avionics: "AN/APG-82(V)1 AESA; EPAWSS EW.",
      weapons: "Up to 22 air-to-air missiles.",
      stealth: "Minimal. Relies on stand-off."
    },
    ratings: { airToAir: 9, bvr: 9.5, dogfight: 7.5, avionics: 9.5, stealth: 3, multirole: 9.5, survivability: 8, overall: 8.4 },
    comparativeAnalysis: ["Unmatched payload.", "Large RCS.", "High persistence."],
    futureOutlook: "Replacing older C/D models.",
    relatedIds: ["SU35-FLANKER", "J16-FLANKER"]
  },
  {
    id: "SU35-FLANKER",
    name: "Su-35S Flanker-E",
    country: "Russia",
    generation: "4++",
    primaryRole: "Air Superiority",
    status: "Active",
    manufacturer: "Sukhoi",
    firstFlight: "2008-02-19",
    unitCost: "$65M - $85M",
    summary: "The ultimate Flanker variant. It features extreme maneuverability through 3D thrust vectoring and a powerful Irbis-E PESA radar.",
    techProfile: {
      airframe: "Enhanced Su-27 airframe; Thrust vectoring.",
      propulsion: "2 × AL-41F1S.",
      performance: "Mach 2.25; Exceptional agility.",
      avionics: "Irbis-E PESA; OLS-35 IRST.",
      weapons: "12 hardpoints; R-37M; R-77-1.",
      stealth: "Reduced but still large signature."
    },
    ratings: { airToAir: 9.2, bvr: 8.8, dogfight: 10, avionics: 8, stealth: 4, multirole: 8.5, survivability: 8.5, overall: 8.6 },
    comparativeAnalysis: ["Best dogfighter.", "PESA radar lags Western AESA.", "High range/payload."],
    futureOutlook: "Upgrades based on combat experience.",
    relatedIds: ["SU57-FELON", "F15EX-EAGLE"]
  },
  {
    id: "J20-MIGHTYDRAGON",
    name: "J-20 Mighty Dragon",
    country: "China",
    generation: "5",
    primaryRole: "Air Superiority",
    status: "Active",
    manufacturer: "Chengdu Aircraft",
    firstFlight: "2011-01-11",
    unitCost: "$110M",
    summary: "China's first stealth fighter. Designed for long-range air superiority and maritime strike missions.",
    techProfile: {
      airframe: "Canard-delta stealth configuration.",
      propulsion: "WS-10B/C; Transitioning to WS-15.",
      performance: "Mach 2.0+; High fuel capacity.",
      avionics: "Modern AESA; EOTS/EODAS sensor suite.",
      weapons: "Internal bays for PL-15 and PL-10.",
      stealth: "Frontal stealth optimization."
    },
    ratings: { airToAir: 9.2, bvr: 9.5, dogfight: 8.5, avionics: 9, stealth: 9, multirole: 8.5, survivability: 9, overall: 9.1 },
    comparativeAnalysis: ["Large range advantage.", "Canards complicate stealth.", "Rapidly maturing tech."],
    futureOutlook: "Mass production underway; J-20S variant testing.",
    relatedIds: ["F22-RAPTOR", "F35-LIGHTNING"]
  },
  {
    id: "GRIPEN-E",
    name: "JAS 39 Gripen E",
    country: "Sweden",
    generation: "4.5",
    primaryRole: "Multirole",
    status: "Active",
    manufacturer: "Saab",
    firstFlight: "2017-06-15",
    unitCost: "$85M",
    summary: "A light multirole fighter designed for distributed road-base operations. It features industry-leading EW and low operating costs.",
    techProfile: {
      airframe: "Lightweight canard-delta; road-capable.",
      propulsion: "1 × GE F414-GE-39E.",
      performance: "Mach 2.0; Supercruise Mach 1.1.",
      avionics: "Raven AESA; Skyward-G IRST; Arexis EW.",
      weapons: "Meteor; IRIS-T; GBU-39.",
      stealth: "Low RCS for its class."
    },
    ratings: { airToAir: 8.5, bvr: 9.2, dogfight: 9, avionics: 9.5, stealth: 6, multirole: 9, survivability: 9, overall: 8.7 },
    comparativeAnalysis: ["Lowest operating cost.", "Superior EW.", "Low payload compared to heavy jets."],
    futureOutlook: "Adopted by Sweden and Brazil.",
    relatedIds: ["F16V-VIPER", "RAFALE"]
  },
  {
    id: "F16V-VIPER",
    name: "F-16V Viper",
    country: "USA",
    generation: "4.5",
    primaryRole: "Multirole",
    status: "Active",
    manufacturer: "Lockheed Martin",
    firstFlight: "2015-10-16",
    unitCost: "$65M",
    summary: "The ultimate F-16 configuration. It adds F-35 derived AESA radar and mission computers to the legendary Fighting Falcon airframe.",
    techProfile: {
      airframe: "Standard F-16 with structural life extension.",
      propulsion: "1 × P&W F100 or GE F110.",
      performance: "Mach 2.0; 9g limit.",
      avionics: "AN/APG-83 SABR AESA.",
      weapons: "AIM-120; AIM-9X; precision munitions.",
      stealth: "Have Glass coatings."
    },
    ratings: { airToAir: 8.5, bvr: 9, dogfight: 9, avionics: 9, stealth: 5, multirole: 9.5, survivability: 8, overall: 8.4 },
    comparativeAnalysis: ["Best cost/performance balance.", "AESA leap in BVR.", "Limited growth potential."],
    futureOutlook: "New production for export markets.",
    relatedIds: ["GRIPEN-E", "J10C-VIGOROUSDRAGON"]
  },
  {
    id: "J10C-VIGOROUSDRAGON",
    name: "J-10C Vigorous Dragon",
    country: "China",
    generation: "4.5",
    primaryRole: "Multirole",
    status: "Active",
    manufacturer: "Chengdu",
    firstFlight: "2013-12-31",
    unitCost: "$45M",
    summary: "China's leading single-engine fighter. It incorporates a DSI intake and AESA radar, offering high performance at a low price point.",
    techProfile: {
      airframe: "Canard delta; DSI intake.",
      propulsion: "1 × WS-10B.",
      performance: "Mach 1.8; Agile.",
      avionics: "AESA radar; IRST.",
      weapons: "PL-15; PL-10; precision strike.",
      stealth: "RCS reduction via DSI."
    },
    ratings: { airToAir: 8.8, bvr: 9.2, dogfight: 9, avionics: 8.8, stealth: 5.5, multirole: 8.5, survivability: 8.2, overall: 8.6 },
    comparativeAnalysis: ["Strong F-16V competitor.", "Weight-saving DSI.", "First domestic-engine production."],
    futureOutlook: "Standard medium fighter of the PLAAF.",
    relatedIds: ["F16V-VIPER", "JF17-BLOCK3"]
  },
  {
    id: "F/A18E-SUPERHORNET",
    name: "F/A-18E/F Super Hornet",
    country: "USA",
    generation: "4.5",
    primaryRole: "Multirole",
    status: "Active",
    manufacturer: "Boeing",
    firstFlight: "1995-11-29",
    unitCost: "$68M",
    summary: "The US Navy's carrier workhorse. Rugged and versatile, it excels in high-alpha maneuvers and multi-mission flexibility.",
    techProfile: {
      airframe: "Larger evolution of the Hornet.",
      propulsion: "2 × GE F414-GE-400.",
      performance: "Mach 1.8; Superior low-speed agility.",
      avionics: "AN/APG-79 AESA.",
      weapons: "11 hardpoints; LRASM; JSOW.",
      stealth: "Frontal RCS reduction."
    },
    ratings: { airToAir: 8.5, bvr: 8.8, dogfight: 8.8, avionics: 9.2, stealth: 5, multirole: 10, survivability: 8.5, overall: 8.6 },
    comparativeAnalysis: ["Unmatched slow-speed handling.", "Lower speed than heavy jets.", "Carrier versatility."],
    futureOutlook: "Block III upgrades entering service.",
    relatedIds: ["RAFALE", "F35-LIGHTNING"]
  },
  {
    id: "JF17-BLOCK3",
    name: "JF-17 Block III",
    country: "Pakistan",
    generation: "4.5",
    primaryRole: "Multirole",
    status: "Active",
    manufacturer: "PAC / CAC",
    firstFlight: "2019-12-15",
    unitCost: "$28M",
    summary: "A budget-friendly 4.5 generation fighter. It provides high-end BVR capability through AESA radar and PL-15 integration.",
    techProfile: {
      airframe: "Lightweight single-engine.",
      propulsion: "1 × RD-93.",
      performance: "Mach 1.6; Agile.",
      avionics: "KLJ-7A AESA; wide-angle HUD.",
      weapons: "PL-15; PL-10; C-802AK.",
      stealth: "Minor RCS reduction via DSI."
    },
    ratings: { airToAir: 8, bvr: 9, dogfight: 8, avionics: 8.5, stealth: 4, multirole: 8.5, survivability: 7.5, overall: 8.1 },
    comparativeAnalysis: ["Most affordable AESA fighter.", "Limited payload.", "Huge upgrade over legacy."],
    futureOutlook: "Primary PAF fighter; active export.",
    relatedIds: ["J10C-VIGOROUSDRAGON", "TEJAS-MK1A"]
  },
  {
    id: "KF21-BORAMAE",
    name: "KF-21 Boramae",
    country: "South Korea",
    generation: "4.5",
    primaryRole: "Multirole",
    status: "Testing",
    manufacturer: "KAI",
    firstFlight: "2022-07-19",
    unitCost: "$70M",
    summary: "A 4.5+ generation fighter with stealth shaping. Block I uses external weapons; Block II will add internal bays for true 5th-gen performance.",
    techProfile: {
      airframe: "Stealth-shaped F-22 likeness.",
      propulsion: "2 × GE F414-GE-400K.",
      performance: "Mach 1.8; High speed focal point.",
      avionics: "Domestic AESA; IRST; EOTS.",
      weapons: "Meteor; IRIS-T; Taurus.",
      stealth: "Highly reduced RCS; external stores limit Block I."
    },
    ratings: { airToAir: 8.5, bvr: 9.2, dogfight: 8.5, avionics: 9, stealth: 7, multirole: 8.5, survivability: 8.5, overall: 8.6 },
    comparativeAnalysis: ["Best non-stealth fighter potential.", "Future stealth growth.", "Rapid development."],
    futureOutlook: "Block I production starting 2024.",
    relatedIds: ["F35-LIGHTNING", "F15EX-EAGLE"]
  }
];
